version: "3"
services:
  neo4j:
    image: neo4j:4.4.9-community
    container_name: neo4j
    privileged: true
    restart: always
    environment:
      - NEO4J_AUTH=neo4j/neo4j123
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - "./data:/var/lib/neo4j/data"
      - "./logs:/var/lib/neo4j/logs"
      - ./tmp:/tmp
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 1024M
    logging:
      driver: "json-file"
      options:
        max-size: "50M"
        max-file: "10"
