version: '3.7'

services:
  zookeeper:
    image: zookeeper:3.6
    restart: always
    ports:
      - "2181:2181"
    volumes:
      - ./zookeeper/data:/data
      - ./zookeeper/logs:/logs
      - ./zookeeper/config:/conf
      - ./zookeeper/datalog:/datalog
    environment:
      # 匿名登录--必须开启
      - ALLOW_ANONYMOUS_LOGIN=yes
      - TZ=Asia/Shanghai
    container_name: zookeeper
    networks:
      - zk-kafka

  kafka:
    image: wurstmeister/kafka
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_HOST_NAME: "127.0.0.1"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
    volumes:
      - ./kafka/data:/kafka
      - ./kafka/logs:/opt/kafka/logs
    depends_on:
      - zookeeper
    container_name: kafka
    networks:
      - zk-kafka

networks:
  zk-kafka:
    name: zk-kafka
    driver: bridge
