version: '3.9'

services:
  bilibili_tool:
    image: zai7lou/bilibili_tool_pro
    container_name: bilibili_tool_pro
    restart: always
    volumes:
      - ./Logs:/app/Logs
      - ./my_crontab:/app/custom_crontab
    tty: true
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - Ray_Security__IsSkipDailyTask=false

      # Cookie字符串（必填）：
      - Ray_BiliBiliCookies__1=buvid3=9A3CE10C-3B08-4E74-76E6-805EA16D785514452infoc; _uuid=10D53B836-21DC-AAAB-8DEA-6FF18F1093A5F14608infoc; LIVE_BUVID=AUTO2216389367074997; rpdid=|(k)~YJR~JRu0J'uYJ)mJY~Ym; fingerprint_s=6c6d1abfa8b120935af0fdcfa03b340b; CURRENT_BLACKGAP=0; nostalgia_conf=-1; buvid_fp_plain=undefined; hit-dyn-v2=1; blackside_state=0; i-wanna-go-back=-1; DedeUserID=57620419; DedeUserID__ckMd5=f64eb2e77c3882a5; buvid_fp=9abb8589625dd216920a3a5ed5c3ca1c; b_ut=5; bsource=search_bing; CURRENT_QUALITY=0; PVID=1; b_timer=%7B%22ffp%22%3A%7B%22333.1007.fp.risk_9A3CE10C%22%3A%2218225F83578%22%2C%22333.788.fp.risk_9A3CE10C%22%3A%2218225FD5675%22%2C%22333.999.fp.risk_9A3CE10C%22%3A%2218225F85B59%22%2C%22777.5.0.0.fp.risk_9A3CE10C%22%3A%22181B82A89DD%22%2C%22333.337.fp.risk_9A3CE10C%22%3A%22182245B66E3%22%2C%22444.41.fp.risk_9A3CE10C%22%3A%22181FD2F5546%22%2C%22333.976.fp.risk_9A3CE10C%22%3A%22182238D9B45%22%2C%22888.69503.fp.risk_9A3CE10C%22%3A%22181D32DE29F%22%2C%22666.5.fp.risk_9A3CE10C%22%3A%22181DC0B9D13%22%2C%22666.25.fp.risk_9A3CE10C%22%3A%22181F25DB64A%22%2C%22888.70374.fp.risk_9A3CE10C%22%3A%221821936E117%22%2C%22333.937.fp.risk_9A3CE10C%22%3A%2218220619A14%22%7D%7D; b_lsid=A55B61810_18258487B9B; buvid4=48C8020B-08E9-0645-85A9-473BE98EF0A652001-022012414-evRppYb%2FndTx9AwT1TJxdg%3D%3D; fingerprint3=f95cc1d939a764c60dde795fd0db82ef; fingerprint=80008a75f3be9b85ae444d23ba4e2104; SESSDATA=798da0bf%2C1676903621%2Cb50a8%2A81; bili_jct=f80bfaae53ae878e63032532c7dc21fb; sid=5p08g3pu; bp_video_offset_57620419=698181379715760100; CURRENT_FNVAL=16; innersign=0
      # UA：
      - Ray_Security__UserAgent=
      # 开始运行前随机随眠最大分钟数：
      - Ray_Security__RandomSleepMaxMin=
      # 调用接口间的间隔秒数：
      - Ray_Security__IntervalSecondsBetweenRequestApi=

      # 目标投币数量：
      - Ray_DailyTaskConfig__NumberOfCoins=5

      # 天选抽奖指定排除关键字
      - Ray_LiveLotteryTaskConfig__ExcludeAwardNames=
      # 天选抽奖指定包含关键字
      - Ray_LiveLotteryTaskConfig__IncludeAwardNames=

      # 企业微信推送地址：
      - Ray_Serilog__WriteTo__4__Args__webHookUrl=
      # 钉钉：
      - Ray_Serilog__WriteTo__5__Args__webHookUrl=
      # PushPlus推送：
      - Ray_Serilog__WriteTo__9__Args__token=cf6bfc637adc43b49603690895799a9f
      - Ray_Serilog__WriteTo__9__Args__topic=
      - Ray_Serilog__WriteTo__9__Args__channel=wechat
      - Ray_Serilog__WriteTo__9__Args__webhook=
      # Server酱推送scKey：
      - Ray_Serilog__WriteTo__6__Args__turboScKey=
