version: '3.2'

services:
  redis:
    image: redis:6.2.7
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      # 映射配置文件和数据目录
      - ./conf/redis.conf:/etc/redis/redis.conf
      - ./data:/data
      - ./logs:/logs
    command: [ "redis-server", "/etc/redis/redis.conf" ]
    privileged: true
    deploy:
      resources:
        limits:
          cpu: '0.50'
          memory: 200M
        reservations:
          memory: 100M