version: '3.2'

services:
  zookeeper:
    image: zookeeper
    restart: always
    ports:
      - "2181:2181"
    volumes:
      - ./zookeeper/data:/data
      - ./zookeeper/logs:/logs
      - ./zookeeper/config:/conf
      - ./zookeeper/datalog:/datalog
    container_name: zookeeper
    networks:
      - zk-kafka

  kafka:
    image: wurstmeister/kafka
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_HOST_NAME: "127.0.0.1"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
    volumes:
      - ./kafka:/kafka
    depends_on:
      - zookeeper
    container_name: kafka
    networks:
      - zk-kafka

networks:
  zk-kafka:
    name: zk-kafka
    driver: bridge
