version: '3.5'

services:
  postgres:
    container_name: postgres
    image: postgres:14.5
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: data/postgres
    volumes:
      - ./postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: always
    privileged: true

networks:
  postgres:
    name: postgres
    driver: bridge
