version: '3.5'

services:
  postgres:
    container_name: postgres
    image: postgres:15.1-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: data/postgres
      TZ: "Asia/Shanghai"
    volumes:
      - ./data:/data/postgres

    ports:
      - "15432:5432"
    networks:
      - postgres
    restart: always
    privileged: true

networks:
  postgres:
    name: postgres
    driver: bridge
